---
title: "Workspace"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
runtime: shiny
resource_files:
- Data/Shapefiles/County shapefiles/MNCounties_MNDOT.cpg
- Data/Shapefiles/County shapefiles/MNCounties_MNDOT.dbf
- Data/Shapefiles/County shapefiles/MNCounties_MNDOT.prj
- Data/Shapefiles/County shapefiles/MNCounties_MNDOT.sbn
- Data/Shapefiles/County shapefiles/MNCounties_MNDOT.sbx
- Data/Shapefiles/County shapefiles/MNCounties_MNDOT.shp.xml
- Data/Shapefiles/County shapefiles/MNCounties_MNDOT.shx
---

<link rel="stylesheet" href="styles.css" type="text/css">


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(tidyverse)
library(sf)
library(ggrepel)
library(scales)
library(shiny)
library(shinycssloaders)
library(ggiraph)
library(kableExtra)
library(rmapshaper)
library(cowplot)
library(DT)
```

```{r loading jon docs and shapefiles, cache=TRUE}
theme_bar <- theme_bw() +
  theme(panel.grid.major = element_line(color = "grey70", size = 0.1),
        panel.grid.minor = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_text(face = "bold"),
        panel.border = element_blank(),
        legend.background = element_rect(fill = "transparent", color = "transparent"),
        legend.key = element_rect(fill = "transparent"),
        legend.title = element_blank(),
        text = element_text(size = 15),
        plot.caption = element_text(hjust = 0.5, face = "italic"),
        legend.text = element_text(margin = margin(l = 2, r = 5)))

theme_line <- theme_bw() +
  theme(legend.background = element_rect(fill = "transparent", color = "transparent"),
        legend.key = element_rect(fill = "transparent"),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_line(color = "grey70", size = 0.1),
        axis.ticks = element_blank(),
        axis.text = element_text(face = "bold"),
        panel.border = element_blank(),
        text = element_text(size = 15),
        plot.caption = element_text(hjust = 0.5, face = "italic"),
        legend.text = element_text(margin = margin(l = 2, r = 5)))

theme_sf <- theme_bw() +
  theme(axis.text.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks=element_blank(),
        panel.background = element_blank(),
        panel.grid.major = element_line(color = "white"),
        panel.border = element_blank(),
        plot.title = element_text(hjust = 0.5),
        legend.title = element_blank(),
        text = element_text(size = 15),
        plot.caption = element_text(hjust = 0.5, face = "italic"),
        legend.text = element_text(margin = margin(l = 2, r = 5)))

counties.regions <- read_csv("Data/Join docs/county_regions.csv") %>%
  mutate(countyfp = formatC(countyfp, width = 3, flag = "0"),
         Name = str_to_title(Name),
         Name = str_replace(Name, "Q", "q"),
         Name = str_replace(Name, "Of The", "of the"),
         Dem_Desc = ifelse(Name == "Minnesota", "Minnesota", Dem_Desc))

regions = counties.regions %>%
  select(5,6) %>%
  distinct(edr, .keep_all = TRUE)

edr.pr <- counties.regions %>%
  distinct(edr, .keep_all = TRUE) %>%
  select(5,6) %>%
  mutate(edr = str_replace(edr, "  ", " "),
         planning.region = str_replace(planning.region, " Minnesota", ""))

color.ruca <- c("Entirely rural" = "#5CA81F", "Town/rural mix" = "#C7EF99", "Urban/town/rural mix" = "#d8b365", "Entirely urban" = "#a6611a", "Minnesota" = "black")

color.pr <- c("Northwest" = "#810f7c","Northeast" = "#fe9929", "Central" = "#076324", "Seven County Mpls-St Paul" = "#d8b365", "Southwest" = "#1f78b4", "Southeast" = "#d7301f", "Minnesota" = "black")

color.edr <- c("EDR 1 - Northwest" = "#b3cde3", "EDR 2 - Headwaters" = "#8c96c6", "EDR 3 - Arrowhead" = "#fe9929", "EDR 4 - West Central" = "#8856a7", "EDR 5 - North Central" = "#810f7c", "EDR 6E- Southwest Central" = "#e5f5f9", "EDR 6W- Upper Minnesota Valley" = "#bdc9e1", "EDR 7E- East Central" = "#99d8c9", "EDR 7W- Central" = "#2ca25f", "EDR 8 - Southwest" = "#74a9cf", "EDR 9 - South Central" = "#0570b0", "EDR 10 - Southeast" = "#d7301f", "EDR 11 - 7 County Twin Cities" = "#d8b365", "Minnesota" = "black")

color.counties <- scale_color_brewer(palette = "Dark2",
                       guide = guide_legend(ncol = 3))

mn_counties <- st_read("Data/Shapefiles/county shapefiles/MNCounties_MNDOT.shp", quiet = TRUE) %>%
  ms_simplify(keep = .01, keep_shapes = TRUE)
```

```{r most impacted counties table, cache = TRUE}
impacted.counties.table <- read_csv("Data/Earnings/counties-most-impacted-table.csv")

```

```{r prep farm earnings and total earnings, include = FALSE, cache=TRUE}
farm.earnings.county <- read_csv("Data/Earnings/Master-farm-total-earnings-county-2001-2018.csv") %>%
  mutate(farm.earnings = 1000 * farm.earnings,
         total.earnings = 1000 * total.earnings,
         pct.farm.earnings = farm.earnings / total.earnings) %>%
  group_by(GeoName, countyfp) %>%
  mutate(index.farm.earnings = (farm.earnings - farm.earnings[year==2001]) / farm.earnings[year == 2001]) %>%
  ungroup()

farm.earnings.ruca <- farm.earnings.county %>%
  group_by(Dem_Desc, year) %>%
  summarise(total.earnings = sum(total.earnings),
            farm.earnings = sum(farm.earnings)) %>%
  ungroup() %>%
  group_by(Dem_Desc) %>%
  mutate(index.farm.earnings = (farm.earnings - farm.earnings[year==2001]) / farm.earnings[year == 2001],
         index.total.earnings = (total.earnings - total.earnings[year == 2001]) / total.earnings[year == 2001]) %>%
  ungroup() %>%
  mutate(pct.farm.earnings = farm.earnings / total.earnings,
         Dem_Desc = fct_relevel(Dem_Desc, "Entirely rural", "Town/rural mix", "Urban/town/rural mix", "Entirely urban")) 

farm.earnings.edr <- farm.earnings.county %>%
  group_by(year, edr, planning.region) %>%
  summarise(total.earnings = sum(total.earnings),
            farm.earnings = sum(farm.earnings)) %>%
  ungroup() %>%
  group_by(edr) %>%
  mutate(index.farm.earnings = (farm.earnings - farm.earnings[year==2001]) / farm.earnings[year == 2001],
         index.total.earnings = (total.earnings - total.earnings[year == 2001]) / total.earnings[year == 2001]) %>%
  ungroup() %>%
  mutate(pct.farm.earnings = farm.earnings / total.earnings,
         edr = str_replace(edr, "  ", " "),
         edr = fct_relevel(edr, "EDR 1 - Northwest", "EDR 2 - Headwaters", "EDR 3 - Arrowhead", "EDR 4 - West Central", "EDR 5 - North Central", "EDR 6E- Southwest Central", "EDR 6W- Upper Minnesota Valley", "EDR 7E- East Central", "EDR 7W- Central", "EDR 8 - Southwest", "EDR 9 - South Central", "EDR 10 - Southeast", "EDR 11 - 7 County Twin Cities", "Minnesota"),
         planning.region = str_replace(planning.region, " Minnesota", ""),
         planning.region = fct_relevel(planning.region, "Northwest", "Northeast", "Central", "Seven County Mpls-St Paul", "Southwest", "Southeast"))

farm.earnings.pr <- farm.earnings.county %>%
  group_by(year, planning.region) %>%
  summarise(total.earnings = sum(total.earnings),
            farm.earnings = sum(farm.earnings)) %>%
  ungroup() %>%
  group_by(planning.region) %>%
  mutate(index.farm.earnings = (farm.earnings - farm.earnings[year==2001]) / farm.earnings[year == 2001],
         index.total.earnings = (total.earnings - total.earnings[year == 2001]) / total.earnings[year == 2001]) %>%
  ungroup() %>%
  mutate(pct.farm.earnings = farm.earnings / total.earnings,
         planning.region = str_replace(planning.region, " Minnesota", ""),
         planning.region = fct_relevel(planning.region, "Northwest", "Northeast", "Central", "Seven County Mpls-St Paul", "Southwest", "Southeast"))

```

```{r prep county map peak year of total and farm earnings, include  = FALSE, cache=TRUE}
total.earnings.peak.year.county <- farm.earnings.county %>%
  group_by(GeoName, countyfp) %>%
  top_n(wt = total.earnings, n = 1) %>%
  ungroup() %>%
  mutate(year.bins = cut(year,
                         breaks = c(2001,2009, 2011, 2013, 2015, 2017, 2018),
                         labels = c("Before 2010", "2010-2011", "2012-2013", "2014-2015", "2016-2017", "2018"))) %>%
  rename(te.peak.year = 4) %>%
  left_join(mn_counties[,c(4,7)], by = c("countyfp" = "FIPS_CODE"))

farm.earnings.peak.year.county <- farm.earnings.county %>%
  group_by(GeoName, countyfp) %>%
  top_n(wt = farm.earnings, n = 1) %>%
  ungroup() %>%
  distinct(countyfp, .keep_all = TRUE) %>%
  mutate(year.bins = cut(year,
                         breaks = c(2001,2009, 2011, 2013, 2015, 2017, 2018),
                         labels = c("Before 2010", "2010-2011", "2012-2013", "2014-2015", "2016-2017", "2018"))) %>%
  rename(fe.peak.year = 4) %>%
  left_join(mn_counties[,c(4,7)], by = c("countyfp" = "FIPS_CODE"))
```

```{r prep pct change in total earnings since peak farm, include = FALSE, cache=TRUE}
te.2018.county <- farm.earnings.county %>%
  filter(year == 2018) %>%
  select(3,6) %>%
  rename(total.earnings.2018 = 2)

te.change.since.farm.peak <- farm.earnings.peak.year.county %>%
  left_join(te.2018.county, by = "countyfp") %>%
  select(2,3,4,5,6,11,15,14) %>%
  mutate(te.pct.change = (total.earnings.2018 - total.earnings) / total.earnings,
         te.pct.change.bins = cut(te.pct.change,
                                  breaks = c(-1, -.25, -.1, 0, .1, .25, 1),
                                  labels = c("Greater than -25%", "-25% to -10%", "-10% to 0%", "0% to 10%", "10% to 25%", "Greater than 25%")))
names(te.change.since.farm.peak)
```

```{r prep change in farm earnings as pct of total earnings, include = FALSE, cache = TRUE}

fe.te.2018.county <- farm.earnings.county %>%
  filter(year == 2018) %>%
  rename(farm.earnings.2018 = 5,
         total.earnings.2018 = 6) %>% 
  select(3,5,6)

fe.te.peak.2018.county <- farm.earnings.peak.year.county %>%
  rename(farm.earnings.peak = 5,
         total.earnings.peak = 6) %>%
  left_join(fe.te.2018.county, by = "countyfp") %>%
  mutate(change.fe = farm.earnings.2018 - farm.earnings.peak,
         pct.change.fe = change.fe / farm.earnings.peak,
         change.te = total.earnings.2018 - total.earnings.peak,
         pct.change.te = change.te / total.earnings.peak) %>%
  select(2,3,4,5,15,17,18,6,16,19,20,8:10)

fe.te.peak.2018.negative.county <- fe.te.peak.2018.county %>%
  filter(change.te < 0) %>%
  mutate(pct.fe.of.te.peak = farm.earnings.peak / total.earnings.peak,
         pct.fe.of.te.2018 = farm.earnings.2018 / total.earnings.2018,
         change.pct.fe.of.te = 100 * (pct.fe.of.te.2018 - pct.fe.of.te.peak),
         GeoName = str_replace(GeoName, ", MN", ""))
```

```{r prep farm earnings pct industry loss, include = FALSE, cache= TRUE}
te.fe.drop.county <- fe.te.peak.2018.negative.county %>%
  filter(pct.change.te < -.15 & change.pct.fe.of.te < -15) %>%
  select(1,2,3)

earnings.industry <- read_csv("Data/Earnings/bea-earnings-by-industry-2001-2018.csv") %>%
  mutate(countyfp = str_sub(GeoFIPS, 3, 5))

earnings.industry.2018.county <- earnings.industry %>%
  filter(!LineCode %in% c(35, 82)) %>%
  select(27,7,26) %>%
  rename(earnings.2018 = 3) %>%
  mutate(earnings.2018 = as.numeric(earnings.2018) * 1000)

earnings.industry.peak.county <- earnings.industry %>%
  filter(!LineCode %in% c(35, 82)) %>%
  gather(key = "year", value = "earnings.peak", 9:26) %>%
  mutate(earnings.peak = as.numeric(earnings.peak) * 1000,
         year = as.integer(year)) %>%
  select(9,10,7,11)

earnings.industry.peak.2018.drop.county <- te.fe.drop.county %>%
  left_join(earnings.industry.2018.county, by = c("countyfp")) %>%
  left_join(earnings.industry.peak.county, by = c("countyfp", "fe.peak.year" = "year", "Description")) %>%
  mutate(change.earnings = earnings.2018 - earnings.peak) %>%
  filter(change.earnings < 0) %>%
  group_by(GeoName, countyfp) %>%
  summarise(farm.earnings.change = sum(change.earnings[Description == "Farm earnings"], na.rm = TRUE),
            industry.loss.earnings.change = sum(change.earnings, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(pct.fe.of.total.loss = farm.earnings.change / industry.loss.earnings.change)

```

```{r prep impacted counties map, include = FALSE, cache = TRUE}
impacted.counties.map <- read_csv("Data/Earnings/impacted-counties-map-summary.csv") %>%
  mutate(GeoName = str_replace(GeoName, ", MN", "")) %>%
  left_join(mn_counties[,c(4,7)], by = c("countyfp" = "FIPS_CODE")) %>%
  left_join(impacted.counties.table[,c(1,5:9)], by = c("GeoName" = "County")) %>%
  mutate(impacted.cat = ifelse(is.na(`Total earnings - peak year`), "Not likely impacted by farm earnings", "Likely impacted by farm earnings")) %>%
  filter(GeoName != "Minnesota")
```

```{r map impacted counties}

impacted.counties.map.plot <- ggplot(impacted.counties.map) +
  geom_sf_interactive(aes(fill = impacted.cat, tooltip = paste(GeoName, "\nYear farm earnings peaked: ", fe.peak.year, "\nFarm earning during peak year: ", dollar(farm.earnings.peak), "\nTotal earnings during peak year: ", dollar(farm.earnings.peak), "\nFarm earning 2018: ", dollar(farm.earnings.2018), "\nPercent change in farm earnings since peak year: ", percent(pct.change.fe), "\nTotal earnings 2018: ", dollar(total.earnings.2018), "\nPercent change in total earnings since peak year: ", percent(pct.change.te), sep = ""), data_id = GeoName, geometry = geometry)) +
  scale_fill_manual(values = c("#5CA81F", "white"))+
  theme_sf+
  labs(title="Counties most likely impacted by farm earnings") +
  theme(text = element_text(size = 10))

girafe(ggobj = impacted.counties.map.plot, width_svg = 8) %>%
  girafe_options(opts_selection(type = "none"),
                 opts_toolbar(saveaspng = FALSE) ,
                 opts_sizing(rescale = FALSE))

```